import React from 'react';
import AIInsight from './AIInsight';
import { AI_ABOUT_CONTENT } from '../constants';

const About: React.FC = () => (
    <section id="about" className="relative py-20 bg-primary">
      <AIInsight title="The AI Storyteller">
        <p>
          The entire backstory and philosophy of Aetheria presented here were
          generated by a generative AI.
        </p>
        <p>
          We prompted the AI to create a compelling narrative for a fictional
          restaurant that blends culinary arts with artificial intelligence. The AI
          acted as a creative partner, weaving a tale of innovation and passion
          that forms the very identity of Aetheria.
        </p>
        <p className="font-bold text-accent mt-2">Model Used: Gemini 2.5 Flash</p>
      </AIInsight>
      <div className="container mx-auto px-6 flex flex-col md:flex-row items-center gap-12">
        <div className="md:w-1/2">
          <img src="https://images.unsplash.com/photo-1552566626-52f8b828add9?q=80&w=600&auto=format&fit=crop" alt="Restaurant Interior" className="rounded-lg shadow-2xl w-full h-auto object-cover" />
        </div>
        <div className="md:w-1/2 text-center md:text-left">
          <h2 className="text-4xl font-bold font-serif mb-6 text-accent">Our Story</h2>
          <p className="text-text-primary leading-relaxed">
            {AI_ABOUT_CONTENT.story}
          </p>
        </div>
      </div>
    </section>
);

export default About;
