import React from 'react';
import AIInsight from './AIInsight';
import { AI_HERO_CONTENT } from '../constants';

const Hero: React.FC = () => {
  return (
    <section id="home" className="relative h-screen flex items-center justify-center text-center text-white bg-cover bg-center" style={{ backgroundImage: `url('https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1920&auto=format&fit=crop')` }}>
      <div className="absolute inset-0 bg-black opacity-60"></div>
      <AIInsight title="AI-Crafted Welcome">
        <p>The captivating hero image, title, and welcome text on this page were not written by a human copywriter but generated by a powerful AI.</p>
        <p>We provided the AI with a concept – "an elegant, innovative restaurant fusing technology and cuisine" – and it crafted this compelling introduction to set the perfect tone for your visit.</p>
        <p className="font-bold text-accent mt-2">Model Used: Gemini 2.5 Flash (Text), Imagen 4 (Image Concept)</p>
      </AIInsight>
      <div className="relative z-10 p-6 max-w-3xl animate-fade-in">
        <h2 className="text-5xl md:text-7xl font-bold font-serif mb-4 tracking-wider leading-tight text-shadow-lg">{AI_HERO_CONTENT.title}</h2>
        <p className="text-lg md:text-xl text-text-primary">{AI_HERO_CONTENT.description}</p>
      </div>
    </section>
  );
};

export default Hero;